### PR TITLE
Initial Travis integration.

### PR DESCRIPTION
**Pull request by voxik**
This is initial Travis CI integration PR.

### CODE REVIEW

**Comment by voxik** [comment]
@pvalena Is the Travis integration enabled? Does not look like it is ...

**Comment by pvalena** [comment]
Thanks!

**Comment by voxik** [comment]
@jackorp Could you check the build failure please? It might be due to older Ruby? Not sure.

**Comment by pvalena** [comment]
I'd like to have the test portable, thus fixing the script itself is prefered.

**Comment by jackorp** [comment]
I tried specifying ruby version to newer, but the script fails too... So it is not older ruby problem.
FYI build with [ruby 2.5](https://www.travis-ci.org/jackorp/tools/jobs/362796231) and [ruby 2.4.3](https://www.travis-ci.org/jackorp/tools/jobs/362796232)

**Pull request merged**
