### PR TITLE
Add working tests.

### PR DESCRIPTION
**Pull request by jackorp**
This PR adds basic working tests and based on [PR#2](https://github.com/developer-portal/tools/pull/2) and omits the git --global option.

### CODE REVIEW

**Comment by pvalena** [comment]
Could you modify this PR to add only the basic test (no skipped ones) and squash the commits into one? (f.e.: `git rebase HEAD^^ --interactive`)

We've talked about BDD, which would mean one-PR-per-idea. The PR would then not only contain the test but also the implementation or fix of the get_authors.rb script.

**Comment by pvalena** [comment]
Thinking about it, I do not actually mind the skipped tests, so it's up to you if you want to keep them, but squashing is mandatory:).

**Comment by jackorp** [comment]
I have squashed the commits.
I am thinking I am going to add link as reference to the test in the PR.

**Comment by pvalena** [comment]
Ok, lets test this. In other PR you can enhance `setup` and add more tests.

**Pull request merged**
